language: objective-c
os: osx
osx_image: xcode11.7

script:
- set -o pipefail
- xcodebuild clean build test -project AcessibilityFaceCursor/AcessibilityFaceCursor.xcodeproj -scheme "AcessibilityFaceCursor" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=13.7,name=iPhone 8" ONLY_ACTIVE_ARCH=NO

